# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopAdmin', '0001_initial'),
        ('orderAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dissension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_time', models.DateField(default=datetime.datetime.now, verbose_name='纠纷时间')),
                ('buyer_desc', models.CharField(max_length=100, verbose_name='买家描述')),
                ('seller_desc', models.CharField(default='', max_length=100, verbose_name='卖家描述')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderAdmin.order', verbose_name='订单号')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopAdmin.CnShop', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '纠纷详情',
                'verbose_name_plural': '纠纷详情',
            },
        ),
    ]
