# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateField(default=datetime.datetime.now, verbose_name='下单时间')),
                ('pay_time', models.DateField(null=True, verbose_name='付款时间')),
                ('deliver_time', models.DateField(null=True, verbose_name='发货时间')),
                ('deliver_address', models.CharField(max_length=100, verbose_name='发货地址')),
                ('order_price', models.FloatField()),
                ('postage', models.FloatField(default=0, verbose_name='邮费')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='买家Id')),
            ],
            options={
                'verbose_name': '订单预览',
                'verbose_name_plural': '订单预览',
            },
        ),
    ]
