# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopAdmin', '0001_initial'),
        ('orderAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=15, verbose_name='商品id')),
                ('item_title', models.CharField(max_length=15, verbose_name='商品名')),
                ('item_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('item_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderAdmin.order', verbose_name='订单号')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopAdmin.CnShop', verbose_name='卖家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='买家')),
            ],
            options={
                'verbose_name': '订单子项详情',
                'verbose_name_plural': '订单子项详情',
            },
        ),
    ]
